- build.gradle.kts
- src/main/java/org/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/org/github/_1c_syntax/mdclasses/metadata/ConfigurationBuilder.java
- src/main/java/org/github/_1c_syntax/mdclasses/metadata/additional/ModuleType.java
- src/test/java/org/github/_1c_syntax/mdclasses/ConfigurationOriginTest.java
- src/test/java/org/github/_1c_syntax/mdclasses/ConfigurationVersionTest.java
* Перебор файлов bsl
* Определение типа модуля
> WIP: Типы модулей конфигурации по файлам 

- src/main/java/com/github/_1c_syntax/mdclasses/metadata/configurations/EDTConfiguration.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationEDTTest.java
- src/test/resources/metadata/edt_en/.project
- src/test/resources/metadata/edt_en/.settings/org.eclipse.core.resources.prefs
- src/test/resources/metadata/edt_en/DT-INF/PROJECT.PMF
- src/test/resources/metadata/edt_en/src/CommonModules/CommonModule/CommonModule.mdo
- src/test/resources/metadata/edt_en/src/CommonModules/CommonModule/Module.bsl
- src/test/resources/metadata/edt_en/src/CommonModules/CommonModule1/CommonModule1.mdo
- src/test/resources/metadata/edt_en/src/Configuration/CommandInterface.cmi
- src/test/resources/metadata/edt_en/src/Configuration/Configuration.mdo
- src/test/resources/metadata/edt_en/src/Configuration/MainSectionCommandInterface.cmi
- Исправлена ошибка падения при отсуствии варианта языка конфигурации: по умолчанию считается Английский вариант.
- Добавлена тестовая конфигурация на английском языке
Closes: #26
> Исправление падения на английских EDT конфигурациях

- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/additional/MDOType.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationEDTTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationEMPTYTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationOriginTest.java
Доработан конструктор билдера для возможности создания пустой конфигурации
> Добавлена возможность собирать пустую конфигурацию

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOConfiguration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/additional/UseMode.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationEDTTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationOriginTest.java
- src/test/resources/metadata/edt/src/Configuration/Configuration.mdo
Closes: #49
Добавлены 
- modalityUseMode
- synchronousExtensionAndAddInCallUseMode
- synchronousPlatformExtensionAndAddInCallUseMode
Закрывать после #48
> Модальность и синхронные вызовы

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/utils/Common.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/utils/MDOUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/ParseSupportDataTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MetaDataObjectTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/utils/MDOUtilsTest.java
1. В Configuration добавлена коллекция со всеми дочерними объектами
2. Модифицирован алгритм определения поддержки
Closes: #47
> Все дочерние плюс патч поддержки

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/Command.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/Form.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/Template.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/additional/MDOType.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MetaDataObjectTest.java
- src/test/resources/metadata/original/Catalogs/Справочник1.xml
- src/test/resources/metadata/original/Catalogs/Справочник1/Templates/Макет2.xml
1. [new] Добавил чтение макетов объектов
2. [fix] поправил ошибки при чтении форм и команд
3. [fix] скорректировал формирование ссылок для дочерних объектов с учетом родителя
Closes: #67
> Поддержка макетов

- build.gradle.kts
> Добавил precommit команду для градл

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/EventSubscription.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MetaDataObjectTest.java
> Добавил обработчик подсписки на событие

- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOUtils.java
Исправлена ошибка при заполнении информации о подсистемах
> Исправил NPE

- build.gradle.kts
- src/main/java/com/github/_1c_syntax/mdclasses/deserialize/ChildObjectsDeserializer.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MetaDataObject.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/Subsystem.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/additional/MDOType.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/Common.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/ConfigurationOriginTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/additional/MDOTypeTest.java
Добавил возможность по строковому имени типа или группы (на русском или английском языках) получить MDOType
Closes: #84
> MDOType по строке

- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOUtils.java
> Unknown MDO check

- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/utils/MDOFactoryTest.java
Упрощено хранение языка по умолчанию для конфигурации. Closes: #101
> configuration's default language

- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
> Добавил параллельное чтение дочерних объектов

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/wrapper/DesignerXRItems.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/test/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactoryTest.java
- src/test/resources/metadata/original_broken/Configuration.xml
1. добавлено исправление чтения воженных подсистем
2. добавлено чтение свойства Content для ФО
> Исправления ошибок

- build.gradle.kts
Для упрощения включения в бсл лс с его спринговым slf4j
> Даунгрейд до стабильной версии slf4j

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDODesignerSynonym.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOSynonym.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/wrapper/DesignerProperties.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/wrapper/DesignerSynonym.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDOSynonymTest.java
- src/test/resources/metadata/edt/src/AccountingRegisters/РегистрБухгалтерии1/РегистрБухгалтерии1.mdo
- src/test/resources/metadata/edt/src/AccountingRegisters/РегистрБухгалтерии2/РегистрБухгалтерии2.mdo
- src/test/resources/metadata/edt/src/AccountingRegisters/РегистрБухгалтерии3/РегистрБухгалтерии3.mdo
- src/test/resources/metadata/edt/src/AccumulationRegisters/РегистрНакопления1/РегистрНакопления1.mdo
- src/test/resources/metadata/original/AccountingRegisters/РегистрБухгалтерии1.xml
- src/test/resources/metadata/original/AccountingRegisters/РегистрБухгалтерии2.xml
- src/test/resources/metadata/original/AccountingRegisters/РегистрБухгалтерии3.xml
> Добавлена поддержка синонимов

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOConfiguration.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/wrapper/DesignerProperties.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- src/test/resources/metadata/edt/src/Configuration/Configuration.mdo
- src/test/resources/metadata/original/Configuration.xml
> Свойства конфигурации "Использовать х формы в у приложении" 

- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/additional/ApplicationRunMode.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- src/test/resources/metadata/original_ordinary/Configuration.xml
> #135 / Режим запуска приложения в виде enum

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOPathUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
> #137 / Добавить в MDObjectBase путь к файлу

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/CommonForm.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/Form.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOForm.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOPathUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/FormDataTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- Чтение данных формы из CommonForm
- Общий интерфейс над формами
Closes #138
> #138 / Чтение данных формы из CommonForm

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/FormCommand.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/wrapper/form/DesignerFormCommand.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/FormDataTest.java
- src/test/resources/metadata/original_broken/Form/Form.xml
> #143 / Чтение задвоенных action в командах формы

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/Subsystem.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/SubsystemTest.java
- src/test/resources/metadata/original/Subsystems/ПерваяПодсистема/Subsystems/ПочиненнаяСистема2.xml
> Добавлена защита от зацикливания подсистем

- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
> Добавлен метод получения типов модулей и ссылок на файл по mdoref

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOConfiguration.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- src/test/resources/metadata/edt_ext_broken/.project
- src/test/resources/metadata/edt_ext_broken/.settings/org.eclipse.core.resources.prefs
- src/test/resources/metadata/edt_ext_broken/DT-INF/PROJECT.PMF
- src/test/resources/metadata/edt_ext_broken/src/Configuration/CommandInterface.cmi
- src/test/resources/metadata/edt_ext_broken/src/Configuration/Configuration.mdo
- src/test/resources/metadata/edt_ext_broken/src/Configuration/MainSectionCommandInterface.cmi
- src/test/resources/metadata/edt_ext_broken/src/Roles/Расш1_ОсновнаяРоль/Rights.rights
- src/test/resources/metadata/edt_ext_broken/src/Roles/Расш1_ОсновнаяРоль/Расш1_ОсновнаяРоль.mdo
> #159 / Чтение расширений без свойства defaultLanguage

- .idea/modules.xml
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOConfiguration.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/wrapper/DesignerProperties.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/metadata/additional/DataLockControlMode.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactory.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDOConfigurationTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- src/test/resources/metadata/edt/src/Configuration/Configuration.mdo
- src/test/resources/metadata/edt2/.project
- src/test/resources/metadata/edt_en/src/Configuration/Configuration.mdo
- src/test/resources/metadata/original/Configuration.xml
- src/test/resources/metadata/original_ordinary/Configuration.xml
!!!Breaking change!!!!
Сменился тип данных поля классов Configuration и MDOconfiguration 
Closes: #166
> add support DataLockControlMode.

- .github/workflows/gh-pages.yml
Продолжение работ по созданию сайта на гитстраничках
Closes:
> Сборка статического сайта

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDXdtoPackage.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/XDTOPackageData.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/xdtopackage/XdtoImport.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/xdtopackage/XdtoObjectType.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/xdtopackage/XdtoProperty.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/xdtopackage/XdtoValueType.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/xdtopackage/package-info.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerProperties.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOPathUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDXdtoPackageTest.java
- src/test/resources/metadata/edt/src/XDTOPackages/ПакетXDTO1/Package.xdto
- src/test/resources/metadata/edt/src/XDTOPackages/ПакетXDTO1/ПакетXDTO1.mdo
- src/test/resources/metadata/original/XDTOPackages/ПакетXDTO1.xml
- src/test/resources/metadata/original/XDTOPackages/ПакетXDTO1/Ext/Package.bin
Closes #109
Пока без связи пакетов между собой (не вспомнил кейса)
> Реализована поддержка чтения данных XDTO

- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/converters/DesignerMDOConverter.java
Конструкторы DesignerMDOConverter сделаны конкурентной мапой, во избежание ConcurrentModification
> fix(unmarshall)

- src/main/java/com/github/_1c_syntax/mdclasses/Configuration.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDConfiguration.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/support/ConfigurationInformation.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerProperties.java
- src/test/java/com/github/_1c_syntax/mdclasses/metadata/ConfigurationTest.java
- src/test/resources/metadata/edt/src/Configuration/Configuration.mdo
- src/test/resources/metadata/original/Configuration.xml
Добавлено чтение атрибутов конфигурации "Краткая информация" и "Детальная информация"
Closes #194
> Чтение в Configuration краткой и подробной информации конфигурации

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/AbstractMDO.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/AbstractMDObjectBase.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/attributes/AbstractMDOAttribute.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/HTTPServiceURLTemplate.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/support/MDOReference.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/AbstractMDOTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDAccountingRegisterExtTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDAccountingRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDAccumulationRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDCalculationRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDCatalogTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDChartOfAccountsTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDChartOfCalculationTypesTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDDataProcessorTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDDocumentExtTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDDocumentJournalTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDDocumentTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDHttpServiceTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDInformationRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDIntegrationServiceTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDReportTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDSequenceTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDSubsystemTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDTaskTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDWebServiceTest.java
В MDORefernece Добавлена поддержка русского представления ссылки
+ поправлены тесты, в свяви с необходимостью проверки формирования ссылки
Closes: #205
> MDORefernece на русском

- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/ExtendStaxDriver.java
> fix(reader): #211 / Implementation via XMLInputFactoryImpl

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDCommonAttribute.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/support/DataSeparation.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerProperties.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDCommonAttributeTest.java
> fix(model): #214 / DataSeparation как отдельное перечисление

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDOTemplate.java
С какого-то момента, AbstractMDOObjectBase::getPath теперь возвращает путь к файлу СКД, а не самому шаблону. Доработан mdclasses для возможности получения реального пути к шаблону.
Closes:
> fix(templates)

- src/main/java/com/github/_1c_syntax/mdclasses/common/CompatibilityMode.java
> fix(common): для класса CompatibilityMode добавлен Equals and HashCode

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/attributes/AbstractMDOAttribute.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/support/IndexingType.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerProperties.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDAccountingRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDCatalogTest.java
- src/test/resources/metadata/edt/src/Catalogs/Справочник1/Справочник1.mdo
- src/test/resources/metadata/original/AccountingRegisters/РегистрБухгалтерии1.xml
Добавлено чтение признака индексированности реквизитов
Closes: #224
> Добавлено чтение признака индексированности реквизитов

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDConfiguration.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/MDExchangePlan.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/children/ExchangePlanItem.java
- src/main/java/com/github/_1c_syntax/mdclasses/mdo/support/AutoRecordType.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/XStreamFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerExchangePlanContent.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerProperties.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOFactory.java
- src/main/java/com/github/_1c_syntax/mdclasses/utils/MDOPathUtils.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDConfigurationTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDExchangePlanTest.java
- src/test/resources/metadata/edt/src/ExchangePlans/ПланОбмена1/ПланОбмена1.mdo
- src/test/resources/metadata/original/ExchangePlans/ПланОбмена1.xml
- src/test/resources/metadata/original/ExchangePlans/ПланОбмена1/Ext/Content.xml
- Реализовано чтение состава плана обмена 
- Реализовано чтение признаков РаспределеннаяИнформационнаяБаза и ВключатьРасширенияКонфигурации
Closes: #110
> Реализовано чтение состава плана обмена и признаков УРБД

- src/main/java/com/github/_1c_syntax/mdclasses/mdo/attributes/Dimension.java
- src/main/java/com/github/_1c_syntax/mdclasses/unmarshal/wrapper/DesignerProperties.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDAccountingRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDAccumulationRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDCalculationRegisterTest.java
- src/test/java/com/github/_1c_syntax/mdclasses/mdo/MDInformationRegisterTest.java
- src/test/resources/metadata/edt/src/CalculationRegisters/РегистрРасчета1/РегистрРасчета1.mdo
- src/test/resources/metadata/original/AccumulationRegisters/РегистрНакопления1.xml
- src/test/resources/metadata/original/InformationRegisters/РегистрСведений1.xml
Для измерений добавлены признаки
- Ведущее
- Запрет незаполненных значений
- Использовать в итогах
Closes: #226
> Добавлены атрибуты изменений регистров

- .idea/vcs.xml
- build.gradle.kts
- src/main/java/com/github/_1c_syntax/bsl/mdclasses/CF.java
- src/main/java/com/github/_1c_syntax/bsl/mdclasses/ConfigurationTree.java
- src/main/java/com/github/_1c_syntax/bsl/mdo/ChildrenOwner.java
- src/main/java/com/github/_1c_syntax/bsl/mdo/ModuleOwner.java
- src/main/java/com/github/_1c_syntax/bsl/mdo/Subsystem.java
- src/main/java/com/github/_1c_syntax/bsl/reader/FakeReader.java
- src/test/java/com/github/_1c_syntax/bsl/mdclasses/ConfigurationTest.java
- src/test/java/com/github/_1c_syntax/bsl/mdo/CatalogTest.java
- src/test/resources/fixtures/mdclasses/Configuration.json
- src/test/resources/fixtures/mdclasses/Configuration_edt.json
- src/test/resources/fixtures/mdclasses/Constants.Константа1.json
- src/test/resources/fixtures/mdclasses/Constants.Константа1_edt.json
- src/test/resources/fixtures/mdclasses_ext/Configuration_edt.json
> Подготовка к 0.12

- src/main/java/com/github/_1c_syntax/bsl/mdo/support/RoleRight.java
- src/main/java/com/github/_1c_syntax/bsl/mdo/support/ScriptVariant.java
- Для прав доступа добавлено русское имя
- для прав добавлен метод получения значения по строковому имени
Closes
> Добавлено русское имя для прав доступа

- src/main/java/com/github/_1c_syntax/bsl/reader/common/xstream/ExtendXStream.java
Пропускает битые файлы (в том числе дочерние) с выводом пути к файлу и описания проблемы (если удалось понять).
Пример
```log
2025-03-25 12:23:45 DEBUG Чтения файла поставки ParentConfigurations.bin, полное чтение = false
2025-03-25 12:23:45 DEBUG Найдено конфигураций: 0
2025-03-25 12:23:45 ERROR Can't read file '/home/valery/reps/configuration/src/Roles/BrokenRole/Rights.rights' - it's broken (skipped): ParseError at [row,col]:[1,7]
Message: A pseudo attribute name is expected.
```
Closes
> Добавлен пропуск битых файлов и вывод компактного описания причины

- src/main/java/com/github/_1c_syntax/bsl/mdclasses/CF.java
- src/main/java/com/github/_1c_syntax/bsl/mdo/MD.java
- src/test/java/com/github/_1c_syntax/bsl/mdo/EnumTest.java
- src/test/java/com/github/_1c_syntax/bsl/test_utils/MDTestUtils.java
1. Добавлены методы быстрого получения строкового представления ссылки MDO
2. Добавлены методы получения локализованного представления ссылки
Closes
> Оптимизация API для получения представления ссылок на объекты, включая локализацию представления
